In [1]:
import numpy as np

In [2]:
phi_1 = np.array([0.1, 0.9])
phi_2 = np.array([[0.3, 0.7], [0.9, 0.1]])
phi_3 = np.array([0.8, 0.2])
phi_4 = np.array([[[0.3, 0.7], [0.8, 0.2]], [[0.1, 0.9], [0.2, 0.8]]])

In [3]:
phi_2[0, :], phi_2[1, :]

(array([0.3, 0.7]), array([0.9, 0.1]))

In [4]:
mu_factor_11 = np.array([0.5, 0.5])
mu_factor_12 = np.array([0.5, 0.5])
mu_factor_22 = np.array([0.5, 0.5])
mu_factor_33 = np.array([0.5, 0.5])
mu_factor_24 = np.array([0.5, 0.5])
mu_factor_34 = np.array([0.5, 0.5])
mu_factor_44 = np.array([0.5, 0.5])

In [5]:
phi_2[0, :]

array([0.3, 0.7])

In [6]:
phi_2[0, 0] * mu_factor_22[0] + phi_2[0, 1] * mu_factor_22[1]

0.5

In [7]:
phi_2[0, 0] * mu_factor_22[0], phi_2[0, 1] * mu_factor_22[1]

(0.15, 0.35)

In [8]:
phi_2[1, 0] * mu_factor_22[0] + phi_2[1, 1] * mu_factor_22[1]

0.5

In [9]:
phi_2 * mu_factor_22

array([[0.15, 0.35],
       [0.45, 0.05]])

In [10]:
np.sum(phi_2 * mu_factor_22, axis=-1)

array([0.5, 0.5])

In [11]:
phi_4

array([[[0.3, 0.7],
        [0.8, 0.2]],

       [[0.1, 0.9],
        [0.2, 0.8]]])

In [12]:
phi_2[0, :] * mu_factor_22, phi_2[1, :] * mu_factor_22

(array([0.15, 0.35]), array([0.45, 0.05]))

In [13]:
np.sum(phi_2[0, :] * mu_factor_22), np.sum(phi_2[1, :] * mu_factor_22)

(0.5, 0.5)

In [14]:
np.sum(phi_2[:, 0] * mu_factor_12), np.sum(phi_2[:, 1] * mu_factor_12)

(0.6, 0.39999999999999997)

In [15]:
np.sum(
    np.sum(phi_4[0, 0, :] * mu_factor_34[0] * mu_factor_44) + \
    np.sum(phi_4[0, 1, :] * mu_factor_34[1] * mu_factor_44)
), \
np.sum(
    np.sum(phi_4[1, 0, :] * mu_factor_34[0] * mu_factor_44) + \
    np.sum(phi_4[1, 1, :] * mu_factor_34[1] * mu_factor_44)
)

(0.5, 0.5)

In [16]:
for i in range(100):
    mu_node_11 = phi_1
    mu_node_21 = np.array([np.sum(phi_2[0, :] * mu_factor_22), np.sum(phi_2[1, :] * mu_factor_22)])
    
    mu_node_22 = np.array([np.sum(phi_2[:, 0] * mu_factor_12), np.sum(phi_2[:, 1] * mu_factor_12)])
    mu_node_42 = np.sum(
        np.sum(phi_4[0, 0, :] * mu_factor_34[0] * mu_factor_44) + \
        np.sum(phi_4[0, 1, :] * mu_factor_34[1] * mu_factor_44)
    ), \
    np.sum(
        np.sum(phi_4[1, 0, :] * mu_factor_34[0] * mu_factor_44) + \
        np.sum(phi_4[1, 1, :] * mu_factor_34[1] * mu_factor_44)
    )
    
    mu_node_33 = phi_3
    mu_node_43 = np.sum(
        np.sum(phi_4[0, 0, :] * mu_factor_24[0] * mu_factor_44) + \
        np.sum(phi_4[1, 0, :] * mu_factor_24[1] * mu_factor_44)
    ), \
    np.sum(
        np.sum(phi_4[0, 1, :] * mu_factor_24[0] * mu_factor_44) + \
        np.sum(phi_4[1, 1, :] * mu_factor_24[1] * mu_factor_44)
    )
    
    mu_node_44 = np.sum(
        np.sum(phi_4[:, 0, 0] * mu_factor_34[0] * mu_factor_24) + \
        np.sum(phi_4[:, 1, 0] * mu_factor_34[1] * mu_factor_24)
    ), \
    np.sum(
        np.sum(phi_4[:, 0, 1] * mu_factor_34[0] * mu_factor_24) + \
        np.sum(phi_4[:, 1, 1] * mu_factor_34[1] * mu_factor_24)
    )
    
    mu_factor_11 = mu_node_21
    mu_factor_12 = mu_node_11
    mu_factor_22 = mu_node_42
    mu_factor_33 = mu_node_43
    mu_factor_24 = mu_node_22
    mu_factor_34 = mu_node_33
    mu_factor_44 = np.array([0.5, 0.5])
    
    print(mu_node_44)

(0.35, 0.65)
(0.28800000000000003, 0.712)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448)
(0.35520000000000007, 0.6448

In [17]:
mu_node_11, mu_node_21, mu_node_22, mu_node_42, mu_node_33, mu_node_43, mu_node_44

(array([0.1, 0.9]),
 array([0.5, 0.5]),
 array([0.84, 0.16]),
 (0.5, 0.5),
 array([0.8, 0.2]),
 (0.5, 0.5000000000000001),
 (0.35520000000000007, 0.6448))

In [18]:
mu_node_1 = mu_node_11 * mu_node_21
mu_node_2 = mu_node_22 * mu_node_42
mu_node_3 = mu_node_33 * mu_node_43
mu_node_4 = mu_node_44

In [19]:
mu_node_1, mu_node_2, mu_node_3, mu_node_4

(array([0.05, 0.45]),
 array([0.42, 0.08]),
 array([0.4, 0.1]),
 (0.35520000000000007, 0.6448))

In [20]:
num_vars = 4
nums_confs = np.array([2, 2, 2, 2])
nodes2factors = np.array(
    [
        [1, 1, 0, 0],
        [0, 1, 0, 1],
        [0, 0, 1, 1],
        [0, 0, 0, 1]
    ]
)
factors2nodes = nodes2factors.T
phis = np.array(
    [
        [0.1, 0.9],
        [0.3, 0.7, 0.9, 0.1],
        [0.8, 0.2],
        [0.3, 0.7, 0.8, 0.2, 0.1, 0.9, 0.2, 0.8]
    ]
)

In [21]:
def get_idxes(np_arr):
    idxes = [np.prod(nums_confs[i+1:]) for i in np.where(np_arr == 1)[0][::-1]]
    
    return idxes

def uint2bits(arr, num_bits):
    '''
        convert (numpyarray of uint => array of num_bits bits) for many bits in parallel...

        reference: https://stackoverflow.com/questions/18296035/how-to-extract-the-bits-of-larger-numeric-numpy-data-types
    '''
    arr = arr.astype(np.uint32)
    arr_shape = arr.shape
    arr_flat = arr.flatten()
    out_arr = np.zeros((len(arr_flat), num_bits))
    for i in range(num_bits):
        out_arr[:, i] = (arr_flat >> i) & 1
    out_arr = out_arr.reshape(arr_shape +(num_bits,)).astype(np.int32)
    
    return out_arr

In [22]:
idxes = [get_idxes(nodes) for nodes in factors2nodes]
print(idxes)
total_num_confs = np.prod(nums_confs)
phi_func = np.array(
    [
        [
            phi[i // idx_list[0] % len(phi)] for i in range(total_num_confs)
        ] for idx_list, phi in zip(idxes, phis)
    ]
)
# for idx_list, phi in zip(idxes, phis):
#     print(idx_list)
#     for i in range(total_num_confs):
#         print(phi[i // idx_list[0] % len(phi)])

[[8], [4, 8], [2], [1, 2, 4]]


In [23]:
phi_func

array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.9, 0.9, 0.9, 0.9, 0.9,
        0.9, 0.9, 0.9],
       [0.3, 0.3, 0.3, 0.3, 0.7, 0.7, 0.7, 0.7, 0.9, 0.9, 0.9, 0.9, 0.1,
        0.1, 0.1, 0.1],
       [0.8, 0.8, 0.2, 0.2, 0.8, 0.8, 0.2, 0.2, 0.8, 0.8, 0.2, 0.2, 0.8,
        0.8, 0.2, 0.2],
       [0.3, 0.7, 0.8, 0.2, 0.1, 0.9, 0.2, 0.8, 0.3, 0.7, 0.8, 0.2, 0.1,
        0.9, 0.2, 0.8]])

In [24]:
idxes

[[8], [4, 8], [2], [1, 2, 4]]

In [25]:
factors2nodes

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 1]])

In [26]:
mu_factors = np.array(
    [
        [
            [node]*nums_confs[i] for i, node in enumerate(nodes)
        ] for nodes in factors2nodes
    ]
)

In [27]:
mu_factors[factors2nodes == 1].shape

(7, 2)

In [28]:
mu_factors[0]

array([[1, 1],
       [0, 0],
       [0, 0],
       [0, 0]])

In [29]:
factors2nodes

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 1]])

In [30]:
from itertools import product
from copy import deepcopy


class MarkovRandomField():
    def __init__(self, nodes, factors):
        self.nodes = nodes
        self.factors = factors
        
        self.num_nodes = len(self.nodes)
        self.num_factors = len(self.factors)
        
        self.adj_mtx = self.get_adj_mtx() # [num_nodes, num_factors]
        for row, node in zip(self.adj_mtx, self.nodes):
            node.init_mus(row, self.factors)
        for factor in self.factors:
            factor.init_mus()
    
    def belief_propagation(self, steps):
        for i in range(steps):
            for factor in self.factors:
                new_mus = factor.update_mu()
                factor.mus = new_mus
            for node in self.nodes:
                new_mus = node.update_mu()
                node.mus = new_mus
    
    def get_adj_mtx(self):
        adj_mtx = np.zeros([self.num_nodes, self.num_factors])
        
        for i, node in enumerate(self.nodes):
            for j, factor in enumerate(self.factors):
                adj_mtx[i, j] = 1 if node in factor.nodes else 0
        
        return adj_mtx

    
class Node():
    def __init__(self, name, vals):
        self.name = name
        self.vals = vals
        self.vals.sort()
    
    def init_mus(self, adj_mtx_row, factors):
        self.node_idxes = []
        self.factors = []
        self.mus = []
        self.adj_nodes = []
        self.adj_vals = []
        for i in np.where(adj_mtx_row == 1)[0]:
            factor = factors[i]
            node_idx = factor.nodes.index(self)
            
            self.node_idxes.append(node_idx)
            
            self.factors.append(factor)
            self.mus.append({val: 0. for val in self.vals})
            
            adj_nodes = factor.nodes[:]
            adj_nodes.remove(self)
            self.adj_nodes.append(adj_nodes)
            
            adj_vals = list(product(*[adj_node.vals for adj_node in adj_nodes]))
            self.adj_vals.append(adj_vals)
    
    def mu(self, factor_idx, val):
        return self.mus[factor_idx][val]
    
    def update_mu(self):
        new_mus = deepcopy(self.mus)
        for val in self.vals:
            for i, (node_idx, factor, adj_nodes, adj_vals) in enumerate(
                zip(
                    self.node_idxes, self.factors, self.adj_nodes, self.adj_vals
                )
            ):
                if len(adj_nodes) != 0:
                    summation = 0
                    for adj_val in adj_vals:
                        factor_in = list(adj_val[:])
                        factor_in.insert(node_idx, val)
                        prod = factor(tuple(factor_in))
                        for j, adj_node in enumerate(adj_nodes):
                            prod *= factor.mu(adj_node.node_idxes[adj_node.factors.index(factor)], adj_val[j])
                        summation += prod
                    new_mus[i][val] = summation
                else:
                    new_mus[i][val] = factor(val)
        
        return new_mus
    
    def get_marginal_distribution(self):
        P = {}
        for val in self.vals:
            all_mus = [self.mu(i, val) for i in range(len(self.factors))]
            P[val] = np.prod(all_mus)
            
        P_temp = deepcopy(P)
        for val in self.vals:
            P[val] /= np.sum([value for _, value in P_temp.items()])
        
        return P
            

class Factor():
    def __init__(self, name, nodes, maps, val_check=True):
        '''
            name: The name of this factor. e.g. "phi_1"
            nodes: The list of the input names of this factor. e.g. ["X_1", "X_2"]
            maps: The dictionary of the map btw the value tuples of the inputs and the factor output values. e.g.
                {(0, 0): 0.25, (0, 1): 0.25, (1, 0): 0.25, (1, 1): 0.25}
        '''
        self.name = name
        self.nodes = nodes
        self.maps = maps
        if val_check:
            self.val_check()
    
    def __call__(self, vals):
        '''
            An example of this method's usage:
                factor((1, 1)), Result: 0.25
                factor(0), Result: 0.25
        '''
        return self.maps[vals]
    
    def init_mus(self):
        self.mus = []
        self.adj_factors = []
        for node in self.nodes:
            self.mus.append({val: 1/len(node.vals) for val in node.vals}) # Initialize with uniform distribution.
            
            adj_factors = node.factors[:]
            adj_factors.remove(self)
            
            self.adj_factors.append(adj_factors)
    
    def mu(self, node_idx, val):
        return self.mus[node_idx][val]
    
    def update_mu(self):
        new_mus = deepcopy(self.mus)
        for i, (node, adj_factors) in enumerate(zip(self.nodes, self.adj_factors)):
            for val in node.vals:
                if len(adj_factors) != 0:
                    prod = 1
                    for adj_factor in adj_factors:
                        prod *= node.mu(node.factors.index(adj_factor), val)
                    new_mus[i][val] = prod
                else:
                    new_mus[i][val] = self.mus[i][val]
        
        return new_mus
    
    def val_check(self):
        for i, node in enumerate(self.nodes):
            vals = set()
            for key in self.maps.keys():
                try:
                    vals.add(key[i])
                except:
                    vals.add(key)
            vals = list(vals)
            vals.sort()
            
            if node.vals != vals:
                raise ValueError
                    

In [31]:
X_1 = Node("X_1", [0, 1])
X_2 = Node("X_2", [0, 1])
X_3 = Node("X_3", [0, 1])
X_4 = Node("X_4", [0, 1])

Phi_1 = Factor("Phi_1", [X_1],
   {(0,): 0.1, (1,): 0.9}
)
Phi_2 = Factor("Phi_2", [X_1, X_2],
   {
       (0, 0): 0.3,
       (0, 1): 0.7,
       (1, 0): 0.9,
       (1, 1): 0.1
   }
)
Phi_3 = Factor("Phi_3", [X_3],
   {(0,): 0.8, (1,): 0.2}
)
Phi_4 = Factor("Phi_4", [X_2, X_3, X_4],
   {
       (0, 0, 0): 0.3,
       (0, 0, 1): 0.7,
       (0, 1, 0): 0.8,
       (0, 1, 1): 0.2,
       (1, 0, 0): 0.1,
       (1, 0, 1): 0.9,
       (1, 1, 0): 0.2,
       (1, 1, 1): 0.8
   }
)

nodes = [X_1, X_2, X_3, X_4]
factors = [Phi_1, Phi_2, Phi_3, Phi_4]



In [32]:
mrf = MarkovRandomField(nodes, factors)

In [33]:
mrf.belief_propagation(10)

KeyError: 0

In [ ]:
X_4.get_marginal_distribution()

In [ ]:
X_4.mus

In [ ]:
X_2.adj_nodes

In [ ]:
X_2.adj_vals

In [ ]:
X_2.mus

In [ ]:
Phi_2.adj_factors

In [ ]:
Phi_2.mus

In [ ]:
Phi_1((0,))

In [ ]:
X_2.mus

In [ ]:
mrf.factors[3].nodes[0].name

In [ ]:
l = [1, 2, 3]

In [ ]:
{elem: elem for elem in l}

In [ ]:
for i in product([1, 2], [3, 4]):
    print(i)

In [ ]:
l = {1: 1, 2: 2}

In [ ]:
import copy

ll = copy.deepcopy(l)

In [ ]:
ll